# Generated by Django 3.2.5 on 2021-07-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date', models.DateTimeField()),
                ('news_title', models.CharField(max_length=150, verbose_name='title')),
                ('news_text', models.TextField(verbose_name='text')),
            ],
        ),
    ]
